name: multiinventario
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  test: any
  path: ^1.9.0
  sqflite: ^2.4.1
  sqflite_common_ffi: any
  awesome_dialog: ^3.2.1
  pinput: ^5.0.1
  mailer: ^6.4.1
  encrypt: ^5.0.3
  flutter_dotenv: ^5.2.1
  mobile_scanner: ^6.0.5
  go_router: ^14.7.2

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0




flutter:
  uses-material-design: true
  assets: 
  - "lib/assets/imagenes/"
  - "lib/assets/iconos/"
  - "lib/.env"

