name: multiinventario
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.0
  sqflite_common_ffi: any
  sqflite_common_ffi_web: any
  sqlite3_flutter_libs: ^0.5.30
  awesome_dialog: ^3.2.1
  pinput: ^5.0.1
  mailer: ^6.4.1
  encrypt: ^5.0.3
  flutter_dotenv: ^5.2.1
  mobile_scanner: ^6.0.5
  go_router: ^14.7.2
  image_picker: ^1.1.2
  flutter_slidable: ^4.0.0
  path_provider: ^2.1.5  # Eliminada la duplicada
  http: ^1.3.0
  pdf: ^3.10.7
  flutter_pdfview: ^1.3.2  # Eliminada la duplicada
  share_plus: ^7.2.2  # Actualizada a la versión más reciente
  printing: ^5.11.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
  - "lib/assets/imagenes/"
  - "lib/assets/iconos/"
  - "lib/.env"

